runtime: php55
api_version: 1
threadsafe: true

handlers:
  # Landing Page
  - url: /
    script: index.php
    static_dir: index

  # Allow multi-pages
  - url: /(.+\.php)$
    script: \1

  # Upload images
  - url: /(.+\.(gif|png|jpg|svg|ico|jpeg))$
    static_files: \1
    upload: .+\.(gif|png|jpg|svg|ico|jpeg)$
    application_readable: true

  # Upload CSS files
  - url: /css/(.*\.(css|scss))$
    static_files: css/\1
    upload: css/.*\.(css|scss)$

  # Upload JavaScript files
  - url: /js/(.*\.(js))$
    static_files: js/\1
    upload: js/.*\.(js)$

  # all other pages are a 404
  - url: /.*
    script: notfound.php

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: U^YuNDKb4Oh#pgjOSHkR
  CLOUDSQL_DSN: "mysql:dbname=codex;unix_socket=/cloudsql/codex-bu:asia-southeast2:codex-bu"