runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /
  static_dir: css
- url: /
  static_dir: js
- url: /
  static_dir: assets
