runtime: php72

runtime_config:
  document_root: .

handlers:
# Serve Images as static resources
- url: /(.+\.(gif|png|jpg|svg|ico|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|svg|ico|css|js)$

- url: /.*
  script: auto

entrypoint:
  serve handler.php

# Environment
env_variables:
  CLOUDSQL_USER: root
  CLOUDSQL_DB: codex
  CLOUDSQL_PASSWORD: U^YuNDKb4Oh#pgjOSHkR
  CLOUDSQL_DSN: /cloudsql/codex-bu:asia-southeast2:codex-bu
  GOOGLE_STORAGE_BUCKET: "codex-bu.appspot.com"


